export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const CREATE_TICKET = 'CREATE_TICKET';
export const GET_OPEN_TICKETS = 'GET_OPEN_TICKETS';
export const VIEW_TICKET = 'VIEW_TICKET';

export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const CHANGE_TICKET_STATUS = 'CHANGE_TICKET_STATUS';
export const OWN_TICKET = 'OWN_TICKET';
export const DELETE_OWNERSHIP = 'DELETE_OWNERSHIP';
